blank_issues_enabled: false
contact_links:
    - name: Questions & discussion
      url: https://github.com/ilyassan/ytaudiobar/discussions
      about: Ask a question or start a discussion instead of opening an issue
